baseURL = "https://jamesejr.com/"
languageCode = "en"
defaultContentLanguage = "en"
googleAnalytics = "G-PGXTFKV49B"

title = "James Espinosa"
theme = "hallo"
disableKinds = ["page", "section", "taxonomy", "taxonomyTerm"]

[Author]
  name = "James Espinosa"

[params]
  greeting = "Hello."

  [[params.links]]
    iconset = "fas"
    icon = "envelope"
    title = "E-mail"
    url = "mailto:hello@jamesejr.com"

  [[params.links]]
    iconset = "fas"
    icon = "stream"
    title = "Blog"
    url = "https://blog.jamesejr.com"

  [[params.links]]
    icon = "linkedin"
    title = "LinkedIn"
    url = "https://linkedin.com/in/jamesejr"

  [[params.links]]
    icon = "github"
    title = "GitHub"
    url = "https://github.com/jamesejr"

  [[params.links]]
    icon = "mastodon"
    title = "Mastodon"
    url = "https://infosec.exchange/@jamesejr"

  [[params.links]]
    icon = "x-twitter"
    title = "X"
    url = "https://twitter.com/jamesejr7"

  [[params.links]]
    icon = "instagram"
    title = "Instagram"
    url = "https://instagram.com/jamesejr"

  [params.colors]
    background = "#191a1f"
    foreground = "#edf7ff"
    hover = "#9c9cfb"
