baseURL = "https://jamesejr.com/"
languageCode = "en"
enableInlineShortcodes = true

title = "James Espinosa"
theme = "soho"

summarylength = 10
enableEmoji = true
paginate = 5

[params]
  author = "James Espinosa"
  description = "Threat Detection & Response"

  profilePicture = "images/profile.png"

  copyright = "James Espinosa"
  license = "All rights reserved."
  builtWith = false
  mainSections = ["posts"]

  themeColor = "#2b303b"

  [[params.socialIcons]]
    icon = "fas fa-envelope"
    title = "E-mail"
    url = "mailto:jamesejr@gmail.com"

  [[params.socialIcons]]
    icon = "fa-linkedin"
    title = "LinkedIn"
    url = "https://linkedin.com/in/jamesejr"

  [[params.socialIcons]]
    icon = "fa-github"
    title = "GitHub"
    url = "https://github.com/jamesejr"

  [[params.socialIcons]]
    icon = "fa-twitter"
    title = "Twitter"
    url = "https://twitter.com/jamesejr7"

  [[params.socialIcons]]
    icon = "fa-keybase"
    title = "Keybase"
    url = "https://keybase.io/jamesejr"

[menu]

  [[menu.main]]
    name = "Posts"
    weight = 100
    identifier = "posts"
    url = "/posts/"

  [[menu.main]]
    name = "About"
    weight = 300
    identifier = "about"
    url = "/about/"

[taxonomies]

  category = "categories"
  series = "series"
  tag = "tags"

[markup]

  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "monokai"
    tabWidth = 4
