baseURL = "https://jamesejr.com/"
languageCode = "en"
defaultContentLanguage = "en"

title = "James Espinosa"
theme = "hallo"
disableKinds = ["page", "section", "taxonomy", "taxonomyTerm"]

[Author]
  name = "James Espinosa"

[params]
  greeting = "Hello."

  [[params.links]]
      iconset = "fas"
      icon = "envelope"
      title = "E-mail"
      url = "mailto:jamesejr@gmail.com"

  [[params.links]]
      icon = "linkedin"
      title = "LinkedIn"
      url = "https://www.linkedin.com/in/jamesejr"

  [[params.links]]
      icon = "github"
      title = "GitHub"
      url = "https://github.com/jamesejr"

  [[params.links]]
    icon = "twitter"
    title = "Twitter"
    url = "https://twitter.com/jamesejr7"

  [[params.links]]
    icon = "instagram"
    title = "Instagram"
    url = "https://www.instagram.com/jamesejr"

  [[params.links]]
    iconset = "fas"
    icon = "file-alt"
    title = "Resume"
    url = "#"

  [params.colors]
      background = "#2b303b"
      foreground = "#edf7ff"
      hover = "#ffba82"