name = "blog"
type = "webpack"
account_id = "f540aa83379b29b405a23a55064aeb6d"
zone_id = "57cf8866f09ecdcc16a9bb1b31cb3ab5"
route = "jamesejr.com/*"
workers_dev = false

[site]
bucket = "public"
entry-point = "workers-site"

[env.staging]
workers_dev = true
