name: Deploy Blog

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: actions/checkout@master
      - name: Publish
        uses: cloudflare/wrangler-actions@1.1.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
